-- 1. TABLA DE TRABAJOS (JOBS)
-- Almacena cada servicio realizado
create table jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null, -- Vincula el trabajo al usuario
  client text not null,
  date date not null,
  description text,
  transfer numeric default 0,      -- Ingreso Transferencia
  cash numeric default 0,          -- Ingreso Efectivo
  expense_company numeric default 0, -- Gasto Empresa/Taller
  expense_tech numeric default 0,    -- Gasto Técnico
  applied_commission numeric default 50 -- % de comisión aplicado en ese momento
);

-- Habilitar seguridad (RLS) para que cada usuario solo vea sus datos
alter table jobs enable row level security;

-- Política: Los usuarios pueden ver sus propios trabajos
create policy "User can view their own jobs"
on jobs for select
using (auth.uid() = user_id);

-- Política: Los usuarios pueden insertar sus propios trabajos
create policy "User can insert their own jobs"
on jobs for insert
with check (auth.uid() = user_id);

-- Política: Los usuarios pueden actualizar sus propios trabajos
create policy "User can update their own jobs"
on jobs for update
using (auth.uid() = user_id);

-- Política: Los usuarios pueden eliminar sus propios trabajos
create policy "User can delete their own jobs"
on jobs for delete
using (auth.uid() = user_id);


-- 2. TABLA DE CONFIGURACIÓN (USER_SETTINGS)
-- Almacena el % de comisión preferido por el usuario
create table user_settings (
  user_id uuid references auth.users primary key,
  tech_commission_pct numeric default 50,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar seguridad
alter table user_settings enable row level security;

-- Política: Ver configuración propia
create policy "User can view own settings"
on user_settings for select
using (auth.uid() = user_id);

-- Política: Actualizar/Insertar configuración propia
create policy "User can insert/update own settings"
on user_settings for insert
with check (auth.uid() = user_id);

create policy "User can update own settings"
on user_settings for update
using (auth.uid() = user_id);

-- 3. (OPCIONAL) TRIGGER PARA CREAR SETTINGS AUTOMÁTICAMENTE
-- Esto crea una entrada en user_settings automáticamente cuando alguien se registra
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_settings (user_id, tech_commission_pct)
  values (new.id, 50);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
